# Generated by Django 6.0.4 on 2026-04-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Base_App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemlist",
            name="Category_name",
            field=models.CharField(max_length=40),
        ),
    ]
