# Generated by Django 6.0.4 on 2026-05-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Base_App", "0002_alter_itemlist_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="Image",
            field=models.ImageField(blank=True, null=True, upload_to="Items/"),
        ),
        migrations.AlterField(
            model_name="items",
            name="Item_name",
            field=models.CharField(max_length=40),
        ),
    ]
